image: docker:latest

variables:
- DOCKER_IMAGE_NAME: ubuntu20-php7.4-nginx

services:
- docker:dind

before_script:
- docker info
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY

build:
  stage: build
  script:
  - docker build -t $DOCKER_IMAGE_NAME .
  - docker tag $DOCKER_IMAGE_NAME $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  - docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only:
  - master